version: '3.8'

services:
  nginx:
    build:
        context: backend
        dockerfile: dev/nginx.docker
    volumes:
       - ./src:/var/www/
    ports:
        - "8080:80"
    depends_on:
        - php-fpm

  php-fpm:
    build:
        context: backend
        dockerfile: dev/php-fpm.docker
    volumes:
       - ./src:/var/www/
    depends_on:
      - database
      - mailer
    environment:
        - "DB_PORT=3306"
        - "DB_HOST=mysql"

  php-cli:
    restart: unless-stopped
    build:
      context: backend
      dockerfile: dev/php-cli.docker
    volumes:
      - ./src:/var/www/
    depends_on:
      - database
      - mailer
    environment:
        - "DB_PORT=3306"
        - "DB_HOST=mysql"
    tty: true

  node-cli:
    image: node:16-alpine
    volumes:
        - ./src:/var/www
    working_dir: /var/www
    tty: true

  mysql:
      image: 'mysql/mysql-server:8.0'
      restart: unless-stopped
      volumes:
          - 'storage-mysql:/var/lib/mysql'
      environment:
          - "MYSQL_ROOT_PASSWORD=secret"
          - "MYSQL_USER=app"
          - "MYSQL_PASSWORD=secret"
          - "MYSQL_DATABASE=app"

  mailer:
      image: mailhog/mailhog
      restart: unless-stopped
      ports:
          - "1025:1025"
          - "8082:8025"

volumes:
    storage-mysql: {}
